// Generated by the WOLips Templateengine Plug-in at Apr 10, 2006 11:36:35 PM

import com.webobjects.appserver.*;
import com.webobjects.foundation.*;

public class ColourPickerDemo extends WOComponent {

    public ColourPickerDemo(WOContext context) {
        super(context);
    }
    
	public Integer redValue;
	public Integer greenValue;
	public Integer blueValue;

    public void pushGreenValue(float value) {
    		try {
    			greenValue = new Integer((int)value);
    			NSLog.out.appendln("Green Value: " + greenValue);
    		} catch (Exception e) {
    			e.printStackTrace();
    		}
    }
    
    public void pushRedValue(float value) {
		try {
			redValue = new Integer((int)value);
			NSLog.out.appendln("Red Value: " + redValue);
		} catch (Exception e) {
			e.printStackTrace();
		}
    }
    
    public void pushBlueValue(float value) {
		try {
			blueValue = new Integer((int)value);
			NSLog.out.appendln("Blue Value: " + blueValue);
		} catch (Exception e) {
			e.printStackTrace();
		}
    }
    
    public String hexColorValue() {
    		String red = "00", green = "00", blue = "00";
    		if (greenValue != null) {
    			green = Integer.toHexString(greenValue.intValue());
    		}
    		if (blueValue != null) {
    			blue = Integer.toHexString(blueValue.intValue());
    		} 
    		if (redValue != null) {
    			red = Integer.toHexString(redValue.intValue());
    		}
    		String hexValue = "#" + paddedColor(red) + paddedColor(green) + paddedColor(blue);
    		NSLog.out.appendln("Hex Value: " + hexValue);
    		return hexValue;
    }
    
    protected String paddedColor(String color) {
    		if (color.length() == 1) {
    			return "0" + color;
    		}
    		return color;
    }

}