// Generated by the WOLips Templateengine Plug-in at Apr 7, 2006 11:21:38 AM

import com.webobjects.appserver.*;
import com.webobjects.foundation.*;

public class Main extends WOComponent {

    public Main(WOContext context) {
        super(context);
    }    
    
}