// Generated by the WOLips Templateengine Plug-in at Apr 12, 2006 1:47:27 PM

import com.webobjects.appserver.*;

public class MyComponent extends WOComponent {

    public MyComponent(WOContext context) {
        super(context);
    }

}