// Generated by the WOLips Templateengine Plug-in at Apr 9, 2006 3:06:39 PM

import com.webobjects.appserver.*;

public class DragDropDemo extends WOComponent {

    public DragDropDemo(WOContext context) {
        super(context);
    }

}